# Generated by Django 2.2.3 on 2019-07-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0003_tag_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='tag',
            field=models.ManyToManyField(blank=True, to='sentences.Tag'),
        ),
    ]
